<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Components\Blocks\Graph.razor.css"/>
    <None Remove="Components\Blocks\CurrencyViewerCollection.razor.css"/>
  </ItemGroup>

		
  <ItemGroup>
    <Content Include="Components\Blocks\Graph.razor.css" />
    <None Include="Components\Blocks\CurrencyViewerCollection.razor.css"/>
  </ItemGroup>

</Project>
